[package]
name = "mouse-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = "0.5"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
colored = "3.1.1"
anyhow = "1.0"